default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mumbling_development

test:
  <<: *default
  database: mumbling_test

production:
  <<: *default
  database: mumbling_production
  username: mumbling
  password: <%= ENV['MUMBLING_DATABASE_PASSWORD'] %>
